linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - gocritic
    - goconst
    - godot
    - gosimple
    - gosec
    - goimports
    - bodyclose
    - deadcode
    - errcheck
    - errorlint
    - unconvert
    - containedctx
    - dupl
    - staticcheck
    - structcheck
    - misspell
    - ineffassign
    - unparam
    - typecheck
    - varcheck
    - unused
    - whitespace
    - wastedassign

linters-settings:
  gofmt:
    simplify: true

run:
  go: '1.17'
  timeout: 2m
