linters:
  enable-all: true
  disable:
    - wsl
    - paralleltest
    - nlreturn
    - gochecknoglobals
    - varnamelen
    - gomnd
    - exhaustivestruct
    - exhaustruct
    - wrapcheck

linters-settings:
  gofmt:
    simplify: true
  cyclop:
    max-complexity: 12
run:
  go: '1.17'
  timeout: 2m
