version: 2
jobs:
  build:
    docker:
      - image: golangci/golangci-lint:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-{{ checksum "go.mod" }}
      - run: go get -d
      - save_cache:
          key: pkg-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg"
      - run: make test
